yard-0.6.4 だと以下のようなエラーが発生してしまうので、yard-0.6.3のみを使うように変更しました。 Thank you, https://github.com/totty
Failures:
  1) YardAstEditable children_source {}ブロックの中身を取得
     Failure/Error: fcall.block_content_source.should == %q{      # b2 S
     undefined method `[]' for nil:NilClass
     # ./lib/yard_ast_editable.rb:17:in `block'
     # ./lib/yard_ast_editable.rb:29:in `block_content_source'
     # ./spec/yard_ast_editable_spec.rb:84:in `block (3 levels) in <top (required)>'

  2) YardAstEditable replace_source 一部に対して一部を置換
     Failure/Error: fcall2.block.should_not == nil
     undefined method `[]' for nil:NilClass
     # ./lib/yard_ast_editable.rb:17:in `block'
     # ./spec/yard_ast_editable_spec.rb:132:in `block (3 levels) in <top (required)>'

Finished in 0.11471 seconds
30 examples, 2 failures